version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/BasicActorSamples"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
  - package-ecosystem: "nuget"
    directory: "/EvilCorpDemo"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3