apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 5500
    targetPort: 5500
  type: LoadBalancer
  externalIPs:
  - 172.22.0.11
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "frontend"
        dapr.io/app-port: "5500"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: frontend
        image: localhost:5000/frontend:1
        env:
        - name: APP_PORT
          value: "5500"
        ports:
        - containerPort: 5500
        imagePullPolicy: Never
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
           name: frontend
           port: 
             number: 5500
---