@daprHttp=http://localhost:3500

### Get Dapr actor info
GET {{ daprHttp }}/dapr/config
dapr-app-id: basic-actor-demos

### --- Methods ---

### Say Hello World

POST {{ daprHttp }}/v1.0/actors/HelloWorldActor/user1/method/SayHelloWorld


### Say hello with an input
POST {{ daprHttp }}/v1.0/actors/HelloWorldActor/user2/method/SayHello
Content-Type: application/json

"Rene"

### --- State ---

### Get the saved greeting for the actor with ID user2
### Fails when key is not found

GET {{ daprHttp }}/v1.0/actors/StatefulActor/user2/method/GetGreeting

### Set the greeting for the actor with ID user2
POST {{ daprHttp }}/v1.0/actors/StatefulActor/user2/method/SetGreeting
Content-Type: application/json

"Hello from StatefulActor!"

### Set the greeting using state endpoint for the actor with ID user2
POST {{ daprHttp }}/v1.0/actors/StatefulActor/user2/state
Content-Type: application/json

[
    {
        "operation": "upsert",
        "request": {
            "key": "greeting",
            "value": "Hello from StatefulActor (state endpoint)!"
        }
    }
]

### Get the greeting using state endpoint for the actor with ID user2
GET {{ daprHttp }}/v1.0/actors/StatefulActor/user2/state/greeting


### Set two keys using state endpoint for the actor with ID user2
POST {{ daprHttp }}/v1.0/actors/StatefulActor/user2/state
Content-Type: application/json

[
    {
        "operation": "upsert",
        "request": {
            "key": "greeting",
            "value": "Hello from StatefulActor (state endpoint)!"
        }
    },
    {
        "operation": "upsert",
        "request": {
            "key": "date",
            "value": "{{$datetime iso8601}}"
        }
    }
]

### Set one key, delete anotther using state endpoint for the actor with ID Alex
POST {{ daprHttp }}/v1.0/actors/StatefulActor/user2/state
Content-Type: application/json

[
    {
        "operation": "upsert",
        "request": {
            "key": "greeting",
            "value": "Hello from StatefulActor (state endpoint)!"
        }
    },
    {
        "operation": "delete",
        "request": {
            "key": "date"
        }
    }
]

### --- Timers ---

### Reset snooze for TimerActor
POST {{ daprHttp }}/v1.0/actors/TimerActor/alarmclock1/method/ResetSnoozeCount


### Create Timer
POST {{ daprHttp }}/v1.0/actors/TimerActor/alarmclock1/method/CreateTimer
dapr-app-id: basic-actor-demos


### Delete Timer
DELETE {{ daprHttp }}/v1.0/actors/TimerActor/alarmclock1/timers/snooze
dapr-app-id: basic-actor-demos


### --- Reminders ---

### Set Reminder
POST {{ daprHttp }}/v1.0/actors/ReminderActor/alarmclock2/reminders/snooze
dapr-app-id: basic-actor-demos
Content-Type: application/json

{
    "dueTime" : "0h0m3s0ms",
    "period" : "R3/P0Y0M0W0DT0H0M10S"
}


### Get the greeting using state endpoint for the actor with ID alarmclock2
GET {{ daprHttp }}/v1.0/actors/ReminderActor/alarmclock2/state/snoozecount
dapr-app-id: basic-actor-demos


### Reset the snooze count
POST {{ daprHttp }}/v1.0/actors/ReminderActor/alarmclock2/method/ResetSnoozeCount


### Delete Reminder
DELETE {{ daprHttp }}/v1.0/actors/ReminderActor/alarmclock2/reminders/snooze
dapr-app-id: basic-actor-demos