@daprHttp=http://localhost:3500

### Get Dapr actor info
GET {{ daprHttp }}/dapr/config
dapr-app-id: basic-actor-demos

### --- HelloWorld ---

### Say Hello World

GET {{ daprHttp }}/v1.0/actors/HelloWorldActor/user1/method/SayHelloWorld
dapr-app-id: basic-actor-demos


### Say hello with an input
POST {{ daprHttp }}/v1.0/actors/HelloWorldActor/user2/method/SayHello
dapr-app-id: basic-actor-demos
Content-Type: application/json

"Rene"

### --- State ---

### Set the greeting for the actor with ID user2
POST {{ daprHttp }}/v1.0/actors/StatefulActor/user2/method/SetGreeting
dapr-app-id: basic-actor-demos
Content-Type: application/json

"Hello from StatefulActor!"

### Get the saved greeting for the actor with ID user2
GET {{ daprHttp }}/v1.0/actors/StatefulActor/user2/method/GetGreeting
dapr-app-id: basic-actor-demos

### Set the greeting using state endpoint for the actor with ID user2
POST {{ daprHttp }}/v1.0/actors/StatefulActor/user2/state
dapr-app-id: basic-actor-demos
Content-Type: application/json

[
    {
        "operation": "upsert",
        "request": {
            "key": "greeting",
            "value": "Hello from StatefulActor (state endpoint)!"
        }
    }
]

### Get the greeting using state endpoint for the actor with ID user2
GET {{ daprHttp }}/v1.0/actors/StatefulActor/user2/state/greeting
dapr-app-id: basic-actor-demos


### Set two keys using state endpoint for the actor with ID user2
POST {{ daprHttp }}/v1.0/actors/StatefulActor/user2/state
dapr-app-id: basic-actor-demos
Content-Type: application/json

[
    {
        "operation": "upsert",
        "request": {
            "key": "greeting",
            "value": "Hello from StatefulActor (state endpoint)!"
        }
    },
    {
        "operation": "upsert",
        "request": {
            "key": "date",
            "value": "{{$datetime iso8601}}"
        }
    }
]

### Set one key, delete another using state endpoint for the actor with ID Alex
POST {{ daprHttp }}/v1.0/actors/StatefulActor/user2/state
dapr-app-id: basic-actor-demos
Content-Type: application/json

[
    {
        "operation": "upsert",
        "request": {
            "key": "greeting",
            "value": "Hello from StatefulActor (state endpoint)!"
        }
    },
    {
        "operation": "delete",
        "request": {
            "key": "date"
        }
    }
]

### --- Timers ---

### Reset snooze count for TimerActor
POST {{ daprHttp }}/v1.0/actors/TimerActor/alarmclock1/method/ResetSnoozeCount
dapr-app-id: basic-actor-demos


### Create Timer
POST {{ daprHttp }}/v1.0/actors/TimerActor/alarmclock1/method/CreateTimer
dapr-app-id: basic-actor-demos


### Delete Timer
DELETE {{ daprHttp }}/v1.0/actors/TimerActor/alarmclock1/timers/snooze
dapr-app-id: basic-actor-demos


### --- Reminders ---

### Set Reminder
POST {{ daprHttp }}/v1.0/actors/ReminderActor/alarmclock2/reminders/snooze
dapr-app-id: basic-actor-demos
Content-Type: application/json

{
    "dueTime" : "0h0m2s0ms",
    "period" : "R3/P0Y0M0W0DT0H0M5S"
}


### Get the greeting using state endpoint for the actor with ID alarmclock2
GET {{ daprHttp }}/v1.0/actors/ReminderActor/alarmclock2/state/snoozecount
dapr-app-id: basic-actor-demos


### Reset the snooze count
POST {{ daprHttp }}/v1.0/actors/ReminderActor/alarmclock2/method/ResetSnoozeCount
dapr-app-id: basic-actor-demos

### Delete Reminder
DELETE {{ daprHttp }}/v1.0/actors/ReminderActor/alarmclock2/reminders/snooze
dapr-app-id: basic-actor-demos

### --- Actor to Actor ---

### Call the HelloWorldActor from ActorToActor
POST {{ daprHttp }}/v1.0/actors/ActorToActor/id1/method/CallHelloWorld
dapr-app-id: basic-actor-demos
Content-Type: application/json

"helloWorldId1"