version: '3.8'
services:
  evilcorp-api:
    hostname: evilcorp-api
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 7100:7100
      - 3500:3500
    env_file:
      - .env
    networks:
      - network
    depends_on:
      - redis
      - placement
  evilcorp-api-dapr:
    image: "daprio/daprd:1.12.5"
    command: ["./daprd",
     "-app-id", "evilcorp-api",
     "-app-port", "7100",
     "-dapr-http-port", "3500",
     "-placement-host-address", "placement:50006",
     "-resources-path", "/resources",
     "-log-level","info"]
    volumes:
        - ../resources/:/resources
    depends_on:
      - evilcorp-api
    network_mode: "service:evilcorp-api"

  evilcorp-frontend:
    hostname: evilcorp-frontend
    build: 
      context: ./EvilCorp.FrontEnd
      dockerfile: Dockerfile
    ports:
      - 5500:5500
      - 3501:3501
    env_file:
      - .env
    networks:
      - network

  evilcorp-frontend-dapr:
    image: "daprio/daprd:1.12.5"
    command: ["./daprd",
     "-app-id", "evilcorp-frontend",
     "-app-port", "5500",
     "-dapr-http-port", "3501",
     "-resources-path", "/resources",
     "-log-level","info"]
    volumes:
        - ../resources/:/resources
    depends_on:
      - evilcorp-frontend
    network_mode: "service:evilcorp-frontend"

  placement:
    image: "daprio/dapr:1.12.5"
    command: ["./placement", 
     "-port", "50006",
     "-log-level","warn"]
    networks:
      - network

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - network

networks:
  network: