@daprHttp=http://localhost:3500
@appHttp=http://localhost:7100

### Initialize the actors
POST {{appHttp}}/init
Content-Type: application/json

{
    "EmployeeCount": 5
}

### Start the simulation
POST {{appHttp}}/start

